name: fyc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  fl_chart: ^0.69.2
  flutter:
    sdk: flutter
  http: ^1.2.2
  mesh_gradient: ^1.3.8
  video_player: ^2.9.2
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
